version: '3'
services:
  strategy:
    image: strategy:latest
    build:
      context: .
      dockerfile: Dockerfile
  rsi-strategy:
    container_name: rsi-strategy
    image: rsi-strategy:latest
    depends_on:
      - strategy
    build:
      context: ./rsi-strategy
      dockerfile: Dockerfile
    networks:
      - delphos

networks:
  delphos:
    external: true