version: '3'
services:
  feed:
    image: feed:latest
    build:
      context: .
      dockerfile: Dockerfile
  yahoo-finance-feed:
    image: yahoo-finance-feed:latest
    depends_on:
      - feed
    build:
      context: ./yahoo-finance
      dockerfile: Dockerfile
    networks:
      - dxforge
    ports:
      - "8001:8001"
      - "4001:4001"
#  alpaca-markets-feed:
#    image: alpaca-markets-feed:latest
#    depends_on:
#      - feed
#    build:
#      context: ./alpaca-markets
#      dockerfile: Dockerfile
#    env_file:
#      - ./alpaca-markets/.env
#    networks:
#      - forge

networks:
  dxforge:
    external: true