# Use a base Python image
FROM python:3.10

# Set the working directory in the container
WORKDIR /feed

COPY requirements.txt requirements.txt

# Install any additional dependencies if needed
RUN pip install -r requirements.txt