# Use a base Python image
FROM python:3.10

# Set the working directory in the container
WORKDIR /feed

# Install any additional dependencies if needed
RUN pip install dxlib
RUN pip install websocket-client